/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tsakuma' at '14/11/29 22:47' with Gradle 2.2.1
 *
 * @author tsakuma, @date 14/11/29 22:47
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
